apiVersion: apps/v1
kind: Deployment
metadata:
name: java-app-green
labels:
app: java-app
version: green

spec:
replicas: 2

selector:
matchLabels:
app: java-app
version: green

template:
metadata:
labels:
app: java-app
version: green

```
spec:
  containers:
    - name: java-app

      # This will be dynamically replaced by CI/CD (DO NOT HARDCHANGE)
      image: IMAGE_PLACEHOLDER

      ports:
        - containerPort: 8080

      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

      lifecycle:
        preStop:
          exec:
            command: ["sh", "-c", "sleep 10"]
```

